import { RawPokemonData } from './types';

// Mixed array of strings and objects as per original code structure
export const RAW_POKEMON: (string | RawPokemonData)[] = [
    { name: "Bulbasaur", cardImage: "https://images.pokemontcg.io/sv3pt5/166_hires.png" },
    { name: "Ivysaur", cardImage: "https://images.pokemontcg.io/sv3pt5/167_hires.png" },
    { name: "Venusaur", cardImage: "https://images.pokemontcg.io/sv3pt5/198_hires.png" },
    { name: "Charmander", cardImage: "https://images.pokemontcg.io/sv3pt5/168_hires.png" },
    { name: "Charmeleon", cardImage: "https://images.pokemontcg.io/sv3pt5/169_hires.png" },
    { name: "Charizard", cardImage: "https://images.pokemontcg.io/sv3pt5/199_hires.png" },
    { name: "Squirtle", cardImage: "https://images.pokemontcg.io/sv3pt5/170_hires.png" },
    { name: "Wartortle", cardImage: "https://images.pokemontcg.io/sv3pt5/171_hires.png" },
    { name: "Blastoise", cardImage: "https://images.pokemontcg.io/sv3pt5/200_hires.png" },
    { name: "Caterpie", cardImage: "https://images.pokemontcg.io/sv3pt5/172_hires.png" },
    "Metapod", "Butterfree", "Weedle", "Kakuna", 
    { name: "Beedrill", cardImage: "https://images.pokemontcg.io/swsh10/V_hires.png" },
    "Pidgey", "Pidgeotto", "Pidgeot", "Rattata", "Raticate", "Spearow", "Fearow", "Ekans", "Arbok", 
    { name: "Pikachu", cardImage: "https://images.pokemontcg.io/sv3pt5/173_hires.png" },
    { name: "Raichu", cardImage: "https://images.pokemontcg.io/sv2/211_hires.png" },
    "Sandshrew", "Sandslash", "Nidoran♀", "Nidorina", "Nidoqueen", "Nidoran♂", "Nidorino", 
    { name: "Nidoking", cardImage: "https://images.pokemontcg.io/sv3pt5/174_hires.png" },
    "Clefairy", "Clefable", "Vulpix", 
    { name: "Ninetales", cardImage: "https://images.pokemontcg.io/sv3pt5/186_hires.png" },
    "Jigglypuff", "Wigglytuff", "Zubat", "Golbat", "Oddish", "Gloom", "Vileplume", "Paras", "Parasect", "Venonat", "Venomoth", "Diglett", "Dugtrio", "Meowth", "Persian", 
    { name: "Psyduck", cardImage: "https://images.pokemontcg.io/sv3pt5/175_hires.png" },
    "Golduck", "Mankey", "Primeape", 
    { name: "Growlithe", cardImage: "https://images.pokemontcg.io/swsh8/TG01_hires.png" },
    { name: "Arcanine", cardImage: "https://images.pokemontcg.io/sv1/224_hires.png" },
    "Poliwag", { name: "Poliwhirl", cardImage: "https://images.pokemontcg.io/sv3pt5/176_hires.png" },
    "Poliwrath", "Abra", "Kadabra", 
    { name: "Alakazam", cardImage: "https://images.pokemontcg.io/sv3pt5/201_hires.png" },
    "Machop", { name: "Machoke", cardImage: "https://images.pokemontcg.io/sv3pt5/177_hires.png" },
    { name: "Machamp", cardImage: "https://images.pokemontcg.io/swsh10/V_hires.png" },
    "Bellsprout", "Weepinbell", "Victreebel", "Tentacool", "Tentacruel", "Geodude", "Graveler", "Golem", "Ponyta", 
    { name: "Rapidash", cardImage: "https://images.pokemontcg.io/swsh12/TG11_hires.png" },
    "Slowpoke", "Slowbro", "Magnemite", "Magneton", "Farfetch’d", "Doduo", "Dodrio", "Seel", "Dewgong", "Grimer", "Muk", "Shellder", "Cloyster", "Gastly", "Haunter", 
    { name: "Gengar", cardImage: "https://images.pokemontcg.io/swsh8/271_hires.png" },
    "Onix", "Drowzee", "Hypno", "Krabby", "Kingler", "Voltorb", "Electrode", "Exeggcute", "Exeggutor", "Cubone", "Marowak", "Hitmonlee", "Hitmonchan", "Lickitung", "Koffing", "Weezing", "Rhyhorn", "Rhydon", "Chansey", 
    { name: "Tangela", cardImage: "https://images.pokemontcg.io/sv3pt5/178_hires.png" },
    "Kangaskhan", "Horsea", "Seadra", "Goldeen", "Seaking", "Staryu",
    { name: "Starmie", cardImage: "https://images.pokemontcg.io/swsh10/TG13_hires.png" },
    { name: "Mr. Mime", cardImage: "https://images.pokemontcg.io/sv3pt5/179_hires.png" },
    "Scyther", { name: "Jynx", cardImage: "https://images.pokemontcg.io/sv3pt5/191_hires.png" },
    "Electabuzz", "Magmar", "Pinsir", "Tauros", 
    { name: "Magikarp", cardImage: "https://images.pokemontcg.io/sv2/203_hires.png" },
    { name: "Gyarados", cardImage: "https://images.pokemontcg.io/xy9/123_hires.png" },
    { name: "Lapras", cardImage: "https://images.pokemontcg.io/swsh12pt5/GG05_hires.png" },
    { name: "Ditto", cardImage: "https://images.pokemontcg.io/swsh12pt5/GG22_hires.png" },
    { name: "Eevee", cardImage: "https://images.pokemontcg.io/swsh9/TG11_hires.png" },
    { name: "Vaporeon", cardImage: "https://images.pokemontcg.io/swsh9/TG02_hires.png" },
    { name: "Jolteon", cardImage: "https://images.pokemontcg.io/swsh9/TG04_hires.png" },
    { name: "Flareon", cardImage: "https://images.pokemontcg.io/swsh9/TG01_hires.png" },
    "Porygon", { name: "Omanyte", cardImage: "https://images.pokemontcg.io/sv3pt5/180_hires.png" },
    "Omastar", "Kabuto", "Kabutops", 
    { name: "Aerodactyl", cardImage: "https://images.pokemontcg.io/swsh11/180_hires.png" },
    { name: "Snorlax", cardImage: "https://images.pokemontcg.io/swsh11/TG10_hires.png" },
    { name: "Articuno", cardImage: "https://images.pokemontcg.io/swsh6/169_hires.png" },
    { name: "Zapdos", cardImage: "https://images.pokemontcg.io/sv3pt5/202_hires.png" },
    { name: "Moltres", cardImage: "https://images.pokemontcg.io/swsh6/176_hires.png" },
    "Dratini", { name: "Dragonair", cardImage: "https://images.pokemontcg.io/sv3pt5/181_hires.png" },
    { name: "Dragonite", cardImage: "https://images.pokemontcg.io/swsh7/192_hires.png" },
    { name: "Mewtwo", cardImage: "https://images.pokemontcg.io/swsh12pt5/GG44_hires.png" },
    { name: "Mew", cardImage: "https://images.pokemontcg.io/sv3pt5/151_hires.png" }
];

export const GEN_2_POKEMON = [
    { id: 152, name: "Chikorita" }, { id: 153, name: "Bayleef" }, { id: 154, name: "Meganium" }, { id: 155, name: "Cyndaquil" }, { id: 156, name: "Quilava" }, { id: 157, name: "Typhlosion" }, { id: 158, name: "Totodile" }, { id: 159, name: "Croconaw" }, { id: 160, name: "Feraligatr" },
    { id: 161, name: "Sentret" }, { id: 162, name: "Furret" }, { id: 163, name: "Hoothoot" }, { id: 164, name: "Noctowl" }, { id: 165, name: "Ledyba" }, { id: 166, name: "Ledian" }, { id: 167, name: "Spinarak" }, { id: 168, name: "Ariados" }, { id: 169, name: "Crobat" }, { id: 170, name: "Chinchou" }, { id: 171, name: "Lanturn" },
    { id: 172, name: "Pichu" }, { id: 173, name: "Cleffa" }, { id: 174, name: "Igglybuff" }, { id: 175, name: "Togepi" }, { id: 176, name: "Togetic" }, { id: 177, name: "Natu" }, { id: 178, name: "Xatu" }, { id: 179, name: "Mareep" }, { id: 180, name: "Flaaffy" }, { id: 181, name: "Ampharos" }, { id: 182, name: "Bellossom" },
    { id: 183, name: "Marill" }, { id: 184, name: "Azumarill" }, { id: 185, name: "Sudowoodo" }, { id: 186, name: "Politoed" }, { id: 187, name: "Hoppip" }, { id: 188, name: "Skiploom" }, { id: 189, name: "Jumpluff" }, { id: 190, name: "Aipom" }, { id: 191, name: "Sunkern" }, { id: 192, name: "Sunflora" },
    { id: 193, name: "Yanma" }, { id: 194, name: "Wooper" }, { id: 195, name: "Quagsire" }, { id: 196, name: "Espeon" }, { id: 197, name: "Umbreon" }, { id: 198, name: "Murkrow" }, { id: 199, name: "Slowking" }, { id: 200, name: "Misdreavus" }, { id: 201, name: "Unown" }, { id: 202, name: "Wobbuffet" },
    { id: 203, name: "Girafarig" }, { id: 204, name: "Pineco" }, { id: 205, name: "Forretress" }, { id: 206, name: "Dunsparce" }, { id: 207, name: "Gligar" }, { id: 208, name: "Steelix" }, { id: 209, name: "Snubbull" }, { id: 210, name: "Granbull" }, { id: 211, name: "Qwilfish" }, { id: 212, name: "Scizor" },
    { id: 213, name: "Shuckle" }, { id: 214, name: "Heracross" }, { id: 215, name: "Sneasel" }, { id: 216, name: "Teddiursa" }, { id: 217, name: "Ursaring" }, { id: 218, name: "Slugma" }, { id: 219, name: "Magcargo" }, { id: 220, name: "Swinub" }, { id: 221, name: "Piloswine" }, { id: 222, name: "Corsola" },
    { id: 223, name: "Remoraid" }, { id: 224, name: "Octillery" }, { id: 225, name: "Delibird" }, { id: 226, name: "Mantine" }, { id: 227, name: "Skarmory" }, { id: 228, name: "Houndour" }, { id: 229, name: "Houndoom" }, { id: 230, name: "Kingdra" }, { id: 231, name: "Phanpy" }, { id: 232, name: "Donphan" },
    { id: 233, name: "Porygon2" }, { id: 234, name: "Stantler" }, { id: 235, name: "Smeargle" }, { id: 236, name: "Tyrogue" }, { id: 237, name: "Hitmontop" }, { id: 238, name: "Smoochum" }, { id: 239, name: "Elekid" }, { id: 240, name: "Magby" }, { id: 241, name: "Miltank" }, { id: 242, name: "Blissey" },
    { id: 243, name: "Raikou" }, { id: 244, name: "Entei" }, { id: 245, name: "Suicune" }, { id: 246, name: "Larvitar" }, { id: 247, name: "Pupitar" }, { id: 248, name: "Tyranitar" }, { id: 249, name: "Lugia" }, { id: 250, name: "Ho-Oh" }, { id: 251, name: "Celebi" }
];

export const GEN_3_POKEMON = [
    { id: 252, name: "Treecko" }, { id: 253, name: "Grovyle" }, { id: 254, name: "Sceptile" }, { id: 255, name: "Torchic" }, { id: 256, name: "Combusken" }, { id: 257, name: "Blaziken" }, { id: 258, name: "Mudkip" }, { id: 259, name: "Marshtomp" }, { id: 260, name: "Swampert" },
    { id: 261, name: "Poochyena" }, { id: 262, name: "Mightyena" }, { id: 263, name: "Zigzagoon" }, { id: 264, name: "Linoone" }, { id: 265, name: "Wurmple" }, { id: 266, name: "Silcoon" }, { id: 267, name: "Beautifly" }, { id: 268, name: "Cascoon" }, { id: 269, name: "Dustox" },
    { id: 270, name: "Lotad" }, { id: 271, name: "Lombre" }, { id: 272, name: "Ludicolo" }, { id: 273, name: "Seedot" }, { id: 274, name: "Nuzleaf" }, { id: 275, name: "Shiftry" }, { id: 276, name: "Taillow" }, { id: 277, name: "Swellow" }, { id: 278, name: "Wingull" }, { id: 279, name: "Pelipper" },
    { id: 280, name: "Ralts" }, { id: 281, name: "Kirlia" }, { id: 282, name: "Gardevoir" }, { id: 283, name: "Surskit" }, { id: 284, name: "Masquerain" }, { id: 285, name: "Shroomish" }, { id: 286, name: "Breloom" }, { id: 287, name: "Slakoth" }, { id: 288, name: "Vigoroth" }, { id: 289, name: "Slaking" },
    { id: 290, name: "Nincada" }, { id: 291, name: "Ninjask" }, { id: 292, name: "Shedinja" }, { id: 293, name: "Whismur" }, { id: 294, name: "Loudred" }, { id: 295, name: "Exploud" }, { id: 296, name: "Makuhita" }, { id: 297, name: "Hariyama" }, { id: 298, name: "Azurill" }, { id: 299, name: "Nosepass" },
    { id: 300, name: "Skitty" }, { id: 301, name: "Delcatty" }, { id: 302, name: "Sableye" }, { id: 303, name: "Mawile" }, { id: 304, name: "Aron" }, { id: 305, name: "Lairon" }, { id: 306, name: "Aggron" }, { id: 307, name: "Meditite" }, { id: 308, name: "Medicham" }, { id: 309, name: "Electrike" }, { id: 310, name: "Manectric" },
    { id: 311, name: "Plusle" }, { id: 312, name: "Minun" }, { id: 313, name: "Volbeat" }, { id: 314, name: "Illumise" }, { id: 315, name: "Roselia" }, { id: 316, name: "Gulpin" }, { id: 317, name: "Swalot" }, { id: 318, name: "Carvanha" }, { id: 319, name: "Sharpedo" },
    { id: 320, name: "Wailmer" }, { id: 321, name: "Wailord" }, { id: 322, name: "Numel" }, { id: 323, name: "Camerupt" }, { id: 324, name: "Torkoal" }, { id: 325, name: "Spoink" }, { id: 326, name: "Grumpig" }, { id: 327, name: "Spinda" }, { id: 328, name: "Trapinch" }, { id: 329, name: "Vibrava" }, { id: 330, name: "Flygon" },
    { id: 331, name: "Cacnea" }, { id: 332, name: "Cacturne" }, { id: 333, name: "Swablu" }, { id: 334, name: "Altaria" }, { id: 335, name: "Zangoose" }, { id: 336, name: "Seviper" }, { id: 337, name: "Lunatone" }, { id: 338, name: "Solrock" }, { id: 339, name: "Barboach" }, { id: 340, name: "Whiscash" },
    { id: 341, name: "Corphish" }, { id: 342, name: "Crawdaunt" }, { id: 343, name: "Baltoy" }, { id: 344, name: "Claydol" }, { id: 345, name: "Lileep" }, { id: 346, name: "Cradily" }, { id: 347, name: "Anorith" }, { id: 348, name: "Armaldo" }, { id: 349, name: "Feebas" }, { id: 350, name: "Milotic" },
    { id: 351, name: "Castform" }, { id: 352, name: "Kecleon" }, { id: 353, name: "Shuppet" }, { id: 354, name: "Banette" }, { id: 355, name: "Duskull" }, { id: 356, name: "Dusclops" }, { id: 357, name: "Tropius" }, { id: 358, name: "Chimecho" }, { id: 359, name: "Absol" }, { id: 360, name: "Wynaut" },
    { id: 361, name: "Snorunt" }, { id: 362, name: "Glalie" }, { id: 363, name: "Spheal" }, { id: 364, name: "Sealeo" }, { id: 365, name: "Walrein" }, { id: 366, name: "Clamperl" }, { id: 367, name: "Huntail" }, { id: 368, name: "Gorebyss" }, { id: 369, name: "Relicanth" }, { id: 370, name: "Luvdisc" },
    { id: 371, name: "Bagon" }, { id: 372, name: "Shelgon" }, { id: 373, name: "Salamence" }, { id: 374, name: "Beldum" }, { id: 375, name: "Metang" }, { id: 376, name: "Metagross" }, { id: 377, name: "Regirock" }, { id: 378, name: "Regice" }, { id: 379, name: "Registeel" },
    { id: 380, name: "Latias" }, { id: 381, name: "Latios" }, { id: 382, name: "Kyogre" }, { id: 383, name: "Groudon" }, { id: 384, name: "Rayquaza" }, { id: 385, name: "Jirachi" }, { id: 386, name: "Deoxys" }
];

export const WOTC_BASE_MAP: Record<number, number> = {
    65: 1, 9: 2, 113: 3, 6: 4, 35: 5, 130: 6, 107: 7, 68: 8, 82: 9, 150: 10, 34: 11, 38: 12, 62: 13, 26: 14, 3: 15, 145: 16,
    15: 17, 148: 18, 51: 19, 125: 20, 101: 21, 17: 22, 59: 23, 5: 24, 87: 25, 147: 26, 83: 27, 58: 28, 93: 29, 2: 30, 124: 31,
    64: 32, 14: 33, 67: 34, 129: 35, 126: 36, 33: 37, 61: 38, 137: 39, 20: 40, 86: 41, 8: 42, 63: 43, 1: 44, 10: 45, 4: 46,
    50: 47, 84: 48, 96: 49, 92: 50, 109: 51, 66: 52, 81: 53, 11: 54, 32: 55, 95: 56, 16: 57, 25: 58, 60: 59, 77: 60, 19: 61,
    27: 62, 7: 63, 121: 64, 120: 65, 114: 66, 100: 67, 37: 68, 13: 69
};
